/** Generated by scripts/gen-content-dates.mjs — do not edit by hand.
 *
 * Real last-changed dates from git, used for sitemap <lastmod>. Empty when the
 * build has no git history, in which case the sitemap omits lastmod rather
 * than claiming a date it can't support.
 */
export const ROUTE_DATES: Record<string, string> = {
  "": "2026-08-17",
  "/bedtime-stories": "2026-08-17",
  "/toddler-bedtime-stories": "2026-08-17",
  "/preschool-bedtime-stories": "2026-08-17",
  "/read-aloud-bedtime-stories": "2026-08-17",
  "/bedtime-stories-by-age": "2026-08-17",
  "/cozy-bedtime-stories": "2026-08-17",
  "/lullaby-bedtime-stories": "2026-08-17",
  "/bedtime-stories-app": "2026-08-17",
  "/picture-books-for-kids": "2026-08-17",
  "/stories": "2026-08-17",
  "/collections": "2026-08-17",
  "/faq": "2026-08-17",
  "/guides": "2026-08-18",
  "/privacy": "2026-07-28",
  "/privacy-choices": "2026-07-24",
  "/terms": "2026-07-24",
  "/support": "2026-07-24"
};

/** Story and collection pages are generated from a single data file each. */
export const STORY_DATE = "2026-08-17";
export const COLLECTION_DATE = "2026-08-17";
