#!/usr/bin/env node
/**
 * Copy the app's latest shelf cover thumbnails into public/covers/.
 *
 * Source: moonpage-app/assets/stories/covers/*_cover.webp
 * (generated from each book's p01 by tools/generate-cover-thumbs.mjs)
 *
 * Also writes lib/cover-versions.ts so image URLs cache-bust when covers change.
 *
 * Set MOONPAGE_APP_PATH if the app repo isn't at ../MoonPage/moonpage-app.
 */

import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "fs";
import { join, resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SITE_ROOT = join(__dirname, "..");

function resolveAppRoot() {
  const env = process.env.MOONPAGE_APP_PATH;
  if (env) return resolve(env);
  return resolve(SITE_ROOT, "../MoonPage/moonpage-app");
}

const appRoot = resolveAppRoot();
const srcDir = join(appRoot, "assets/stories/covers");
const destDir = join(SITE_ROOT, "public/covers");

if (!existsSync(srcDir)) {
  console.warn(
    `[sync-covers] App covers not found at ${srcDir} — skipping. Set MOONPAGE_APP_PATH or checkout moonpage-app.`,
  );
  process.exit(0);
}

mkdirSync(destDir, { recursive: true });

const files = readdirSync(srcDir).filter((f) => f.endsWith("_cover.webp"));
const versions = {};

for (const file of files) {
  const src = join(srcDir, file);
  const dest = join(destDir, file);
  cpSync(src, dest, { force: true });
  versions[file] = String(statSync(src).mtimeMs | 0);
}

// Only bump versions for covers listed in lib/stories.ts (site catalog).
const storiesTs = readFileSync(join(SITE_ROOT, "lib/stories.ts"), "utf8");
const catalogFiles = [...storiesTs.matchAll(/file: "(wp_b\d+_\d+_[^"]+_cover\.webp)"/g)].map(
  (m) => m[1],
);

const out = `/** Generated by scripts/sync-covers.mjs — do not edit by hand. */
export const COVER_VERSIONS: Record<string, string> = ${JSON.stringify(
  Object.fromEntries(catalogFiles.filter((f) => versions[f]).map((f) => [f, versions[f]])),
  null,
  2,
)};
`;

writeFileSync(join(SITE_ROOT, "lib/cover-versions.ts"), out);
console.log(`[sync-covers] Synced ${files.length} covers from ${srcDir}`);
